# Generated by Django 4.2.3 on 2023-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=38.9366, max_digits=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='long',
            field=models.DecimalField(decimal_places=4, default=47.2087, max_digits=7),
        ),
    ]
